# src/components/ai_vision/__init__.py

from .core import AIVisionAgent, VisionTask
from .object_detection import (
    ObjectDetector, 
    VideoStreamDetector, 
    ObjectDetectionTask,
    DetectionResult,
    BatchDetectionResult,
    detect_objects,
    detect_objects_batch,
    create_detector
)
from .ocr import (
    OCREngine,
    ImagePreprocessor,
    OCRResult,
    OCRPage,
    OCRBlock,
    OCRLine,
    OCRWord,
    BoundingBox,
    create_ocr_engine,
    extract_text_from_image,
    extract_text_from_images
)
# from .face_recognition import (
#     FaceRecognizer,
#     FaceDetector,
#     FaceEmbedder,
#     FaceDatabase,
#     FaceRecognitionResult,
#     FaceDetection,
#     Identity,
#     FaceRecognitionTask,
#     create_face_recognizer,
#     recognize_faces,
#     enroll_person
# )
# from .face_api import (
#     FaceRecognitionAPI,
#     create_api
# )
from .image_classification import (
    ImageClassifier,
    ImageClassificationTask,
    ClassificationResult,
    TopKResult,
    BatchClassificationResult,
    FineTuningHook,
    LoggingHook,
    CheckpointHook,
    ClassificationModel,
    classify_image,
    classify_images_batch,
    create_classifier
)
from .computer_vision_analytics import (
    ComputerVisionAnalyticsAgent,
    ComputerVisionAnalyticsTask,
    MotionDetector,
    SceneSegmenter,
    VisualReasoner,
    AnalyticsEventEmitter,
    AnalyticsEvent,
    AnalyticsEventType,
    MotionResult,
    SegmentationResult,
    ReasoningResult,
    VisualRule,
    DoorOpenRule,
    ActivityDetectionRule,
    DEFAULT_ANALYTICS_CONFIG,
    analytics_agent
)

__all__ = [
    'AIVisionAgent', 
    'VisionTask',
    'ObjectDetector',
    'VideoStreamDetector',
    'ObjectDetectionTask',
    'DetectionResult',
    'BatchDetectionResult',
    'detect_objects',
    'detect_objects_batch',
    'create_detector',
    'OCREngine',
    'ImagePreprocessor',
    'OCRResult',
    'OCRPage',
    'OCRBlock',
    'OCRLine',
    'OCRWord',
    'BoundingBox',
    'create_ocr_engine',
    'extract_text_from_image',
    'extract_text_from_images',
    # 'FaceRecognizer',
    # 'FaceDetector',
    # 'FaceEmbedder',
    # 'FaceDatabase',
    # 'FaceRecognitionResult',
    # 'FaceDetection',
    # 'Identity',
    # 'FaceRecognitionTask',
    # 'create_face_recognizer',
    # 'recognize_faces',
    # 'enroll_person',
    # 'FaceRecognitionAPI',
    # 'create_api',
    'ImageClassifier',
    'ImageClassificationTask',
    'ClassificationResult',
    'TopKResult',
    'BatchClassificationResult',
    'FineTuningHook',
    'LoggingHook',
    'CheckpointHook',
    'ClassificationModel',
    'classify_image',
    'classify_images_batch',
    'create_classifier',
    # Computer Vision Analytics
    'ComputerVisionAnalyticsAgent',
    'ComputerVisionAnalyticsTask',
    'MotionDetector',
    'SceneSegmenter',
    'VisualReasoner',
    'AnalyticsEventEmitter',
    'AnalyticsEvent',
    'AnalyticsEventType',
    'MotionResult',
    'SegmentationResult',
    'ReasoningResult',
    'VisualRule',
    'DoorOpenRule',
    'ActivityDetectionRule',
    'DEFAULT_ANALYTICS_CONFIG',
    'analytics_agent'
]